### ISSUE TITLE
Encoder from stream

### ISSUE THREAD

**Issue by sengiv** [ejohnson-dotnet/heic2jpg#5]
How to initialize decoder from stream instead of file name?

Below is what I've tried and the error I'm getting.
**CODE**
`var decoder = imagingFactory.CreateDecoderFromStream(heicStream, WICDecodeOptions.WICDecodeMetadataCacheOnLoad, pguidVendor: Guid.Empty);`

**ERROR**
`System.Runtime.InteropServices.COMException: 'The component initialization has failed. (0x88982F8B)'`

_Tried this:_
- get file name from stream than pass that file name to create decoder, failed because no file error
- trace the source of the error when creating from stream (atm testing)

_Runtime Environment_
- I'm running this function in Azure Functions, so .NET support is good and this library builds with no problem.
- Getting file name is not possible, the runtime only has a Stream instance of the image

_PS_
@ejohnson-dotnet, @ejohn54 any help on this problem would be greatly appreciated, thanks!

**Comment by ejohnson-dotnet** [comment]
This will probably never work in Azure.  It requires the HEVC codec to be installed.  Azure does not have this installed on its machines.  You will need to go low level and use https://github.com/nokiatech/heif or some other library that does not need additional codecs.

**Comment by sengiv** [comment]
Thanks for your reply.
I've switched to [HEIF-Utility](https://github.com/liuziangexit/HEIF-Utility) and it works.
